# Generated by Django 5.0.2 on 2024-08-07 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montharchive',
            old_name='month_name',
            new_name='month',
        ),
        migrations.AlterField(
            model_name='montharchive',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_archives', to='api.kid'),
        ),
        migrations.AlterField(
            model_name='montharchive',
            name='missed_days',
            field=models.TextField(),
        ),
    ]
