# Generated by Django 5.0.2 on 2024-08-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_journal_schedule_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='missday_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kid',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kid',
            name='total_sum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
