# Generated by Django 5.0.2 on 2024-08-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stuff_teacher_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'position': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='api.stuff'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='position',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin'), ('assistant', 'Assistant'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
