# Generated by Django 5.0.2 on 2024-08-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kid_missday_cost_kid_tarif_kid_total_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
