# Generated by Django 5.0.2 on 2024-08-05 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_kid_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='kid',
            name='archive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kid', to='api.kidarchive'),
        ),
    ]
