# Generated by Django 5.0.2 on 2024-08-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_group_teacher_alter_stuff_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='stuff',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='stuff',
            name='position',
            field=models.CharField(choices=[('boss', 'Boss'), ('administrator', 'Administrator'), ('teacher', 'Teacher'), ('assistant', 'Assistant'), ('coder', 'Coder'), ('cleaner', 'Cleaner'), ('cook', 'Cook'), ('other', 'Other')], max_length=50),
        ),
    ]
