# Generated by Django 5.0.2 on 2024-08-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_kidarchive_kid_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='missday_cost',
            new_name='missday_count',
        ),
    ]
