# Generated by Django 5.0.2 on 2024-08-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_gender_kid_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montharchive',
            name='left_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='montharchive',
            name='missday_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
