# Generated by Django 5.0.2 on 2024-08-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_missday_cost_kid_missday_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidarchive',
            old_name='data',
            new_name='payment_archive',
        ),
    ]
