# Generated by Django 5.0.2 on 2024-08-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_incometransaction_montharchive_unique_kid_month_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to='api.kid'),
        ),
    ]
