# Generated by Django 5.0.2 on 2024-08-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_data_kidarchive_payment_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidarchive',
            old_name='payment_archive',
            new_name='data',
        ),
    ]
