# Generated by Django 5.0.2 on 2024-08-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_payment_archive_kidarchive_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidarchive',
            old_name='data',
            new_name='payment_archive',
        ),
    ]
