# Generated by Django 5.0.2 on 2024-08-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_data_kidarchive_payment_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kidarchive',
            name='payment_archive',
        ),
        migrations.CreateModel(
            name='YearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='api.kidarchive')),
            ],
        ),
        migrations.CreateModel(
            name='MonthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missed_days', models.JSONField()),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('left_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField()),
                ('missday_count', models.IntegerField()),
                ('missday_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month_name', models.CharField(max_length=20)),
                ('year_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='api.yeardata')),
            ],
        ),
    ]
