# Generated by Django 5.0.2 on 2024-08-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_kidarchive_payment_archive_yeardata_monthdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
