# Generated by Django 5.0.2 on 2024-08-07 22:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='yeardata',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='monthdata',
            name='year_data',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='missday_count',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='tarif',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='total_sum',
        ),
        migrations.CreateModel(
            name='MonthArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month_name', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('missed_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('left_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('missday_count', models.IntegerField(editable=False)),
                ('missday_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField()),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kid')),
            ],
        ),
        migrations.DeleteModel(
            name='KidArchive',
        ),
        migrations.DeleteModel(
            name='MonthData',
        ),
        migrations.DeleteModel(
            name='YearData',
        ),
    ]
